// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// lPOWa
NumericMatrix lPOWa(NumericMatrix a, NumericMatrix tl, NumericVector p);
RcppExport SEXP _hbfm_lPOWa(SEXP aSEXP, SEXP tlSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tl(tlSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(lPOWa(a, tl, p));
    return rcpp_result_gen;
END_RCPP
}
// lVECa
NumericVector lVECa(NumericMatrix a, NumericVector tl, NumericVector p);
RcppExport SEXP _hbfm_lVECa(SEXP aSEXP, SEXP tlSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tl(tlSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(lVECa(a, tl, p));
    return rcpp_result_gen;
END_RCPP
}
// margLik
NumericMatrix margLik(int nh, NumericMatrix a, NumericVector b, NumericVector p, NumericMatrix Y);
RcppExport SEXP _hbfm_margLik(SEXP nhSEXP, SEXP aSEXP, SEXP bSEXP, SEXP pSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nh(nhSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(margLik(nh, a, b, p, Y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hbfm_lPOWa", (DL_FUNC) &_hbfm_lPOWa, 3},
    {"_hbfm_lVECa", (DL_FUNC) &_hbfm_lVECa, 3},
    {"_hbfm_margLik", (DL_FUNC) &_hbfm_margLik, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_hbfm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
