# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lPOWa <- function(a, tl, p) {
    .Call(`_hbfm_lPOWa`, a, tl, p)
}

lVECa <- function(a, tl, p) {
    .Call(`_hbfm_lVECa`, a, tl, p)
}

margLik <- function(nh, a, b, p, Y) {
    .Call(`_hbfm_margLik`, nh, a, b, p, Y)
}

